name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'niku98/ez-form' && github.repository_owner == 'niku98' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish-packages ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
